# docker-compose.yml
# This file sets up five services:
# 1. postgres: A standard row-oriented PostgreSQL database.
# 2. clickhouse: A columnar database for high-performance analytics.
# 3. jupyter: A Jupyter notebook for data analysis and visualization.
# 4. pgadmin: A web-based UI for managing PostgreSQL databases.
# 5. tabix: A web-based UI for managing ClickHouse databases.

version: '3.8'

services:
  # PostgreSQL (Row-Oriented) Service
  postgres:
    image: postgres:latest
    container_name: postgres_row_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data_generation:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network

  # ClickHouse (Columnar) Service
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_columnar_db
    restart: always
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=clickhouse_db
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Jupyter Notebook for Analysis and Visualization
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: data_analyzer
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=datateam
    networks:
      - db_network

  # pgAdmin Web UI Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network
    depends_on:
      - postgres

  # Grafana Web UI for ClickHouse
  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    container_name: grafana_ui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - db_network
    depends_on:
      - clickhouse

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data:
  pgadmin_data: